#BoxLayout:
#   orientation:"vertical"
#   FloatLayout:
#       MultiImage:
#           id:slide_show
#       FingerDrawer:
#           id:finger_draw


#RelativeLayout:
#    size_hint:1, 0.93
#    MultiImage:
#        id:slide_show
#        pos:1,10
#    FingerDrawer:
#        id:finger_draw

AnchorLayout:
    anchor_x:"center"
    anchor_y:"center"
    MultiImage:
        id:slide_show
        anchor_x:"left"
        anchor_y:"top"
    FingerDrawer:
        size_hint:slide_show.size
        id:finger_draw
        anchor_x:"left"
        anchor_y:"top"
    KeyboardListener:
        id:kbd_lstn

