#BoxLayout:
#   orientation:"vertical"
#   FloatLayout:
#       MultiImage:
#           id:slide_show
#       FingerDrawer:
#           id:finger_draw
#   BoxLayout:
#       orientation:"horizontal"
#       size_hint:0.07,0.07
#       Button:
#           id:next_btn
#           text:"Next"
#           on_press: slide_show.nextSlide()
FloatLayout:
    MultiImage:
        id:slide_show
    FingerDrawer:
        id:finger_draw

